Repository crazyinvestor/crazyinvestor, pull requests merged in 2022-10, with the labels that each got.

#38 Websocket 데이터 DB 저장 로직 및 연결 안정성 강화
  engine/b/src/main/java/net/crazyinvestor/engine_b/config/BithumbWSConnectionConfiguration.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/connector/BithumbWSConnector.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/entity/Exchange.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/entity/Quote.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/entity/Symbol.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/entity/Ticker.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/entity/TickerHistory.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/enums/ExchangeName.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/event/BithumbOrderbookDepthEvent.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/event/BithumbTickerEvent.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/event/BithumbTransactionEvent.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/event/DisconnectEvent.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/handler/BithumbWSResponseHandler.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/repository/ExchangeRepository.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/repository/QuoteRepository.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/repository/SymbolRepository.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/repository/TickerHistoryRepository.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/repository/TickerRepository.java
  engine/b/src/main/java/net/crazyinvestor/engine_b/service/TickerService.java
Labels: 기능

#42 Fix: typo error #41
  engine/b/src/main/java/net/crazyinvestor/engine_b/connector/BithumbWSConnector.java
Labels: 버그

#47 JPA OneToOne 관계 사용시 양방향 관계 설정 필요
  engine/b/src/main/java/net/crazyinvestor/engine_b/entity/Symbol.java
Labels: 리팩토링

#49 engine-b 테스트 환경 도커라이징
  engine/b/docker/docker-compose.yml
  engine/b/src/main/resources/application-dev.properties
Labels: 환경설정

#50 Spring 백엔드 서버 초기 파일 생성
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/net/crazyinvestor/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/net/crazyinvestor/backend/BackendApplicationTests.java
Labels: 환경설정
